export const SET_TOASTER_MESSAGE = 'SET_TOASTER_MESSAGE';
export const GET_TOPICS = 'GET_TOPICS';
export const SET_TOPICS = 'SET_TOPICS';
export const RESET_TOASTER = 'RESET_TOASTER';
export const GET_NAMESPACES = 'GET_NAMESPACES';
export const SET_NAMESPACES = 'SET_NAMESPACES';
export const SELECT_NAMESPACE = 'SELECT_NAMESPACE';
export const SET_BUS_CONNECTION_PARAMS = 'SET_BUS_CONNECTION_PARAMS';
